#!/bin/bash
# credit goes to https://www.rohanjain.in/cloudflare-ddns/

TMP_FILE="/tmp/cloudflare-ddns"
API_URL="https://api.cloudflare.com/client/v4"

. /etc/cloudflare-ddns/cloudflare-ddns.conf

# Get previous IP address and record info
if [ -f "$TMP_FILE" ]; then
  read -r ZONE_ID RECORD_ID PREVIOUS_IP RECORD_NAME ZONE_NAME <<<$(jq -r '[.zone_id, .record_id, .ip, .record_name, .zone_name] | @tsv' $TMP_FILE)
fi

CURRENT_IP=$(dig +short -4 myip.opendns.com @resolver1.opendns.com)

# If config file has been changed get a zone id.
if [[ $RECORD_NAME != $DNS_RECORD ]] || [[ $ZONE_NAME != $DNS_ZONE ]]; then
  ZONE_ID=$(
    curl "$API_URL/zones?name=$DNS_ZONE" \
      curl "$API_URL/zones/$ZONE_ID/dns_records?name=$DNS_RECORD" \
      --silent \
      --fail \
      -X GET \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $API_TOKEN" |
      jq -r ".result[0].id"
  )

  if [ $ZONE_ID ]; then
    echo "Found zoneID:$ZONE_ID"
  else
    echo "Connection to Clouflare failed. check credentials."
    exit 1
  fi

  # # Get a record id
  RECORD_ID=$(
    curl "$API_URL/zones/$ZONE_ID/dns_records?name=$DNS_RECORD" \
      --silent \
      --fail \
      -X GET \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $API_TOKEN" |
      jq -r ".result[0].id"
  )
  if [ $ZONE_ID ]; then
    echo "Found recordID:$RECORD_ID"
  else
    echo "zone or record issue. check your config file."
    exit 1
  fi

elif [[ $CURRENT_IP = $PREVIOUS_IP ]]; then
  # If new/previous IPs match, no need for an update.
  echo "No changes occured, IPV4 is $PREVIOUS_IP"
  exit 0
fi

echo "Updating DNS server with IPV4 $CURRENT_IP"

_UPDATE=$(
  cat <<EOF
{ "type": "A",
"name": "$DNS_RECORD",
"content": "$CURRENT_IP"}
EOF
)

curl "$API_URL/zones/$ZONE_ID/dns_records/$RECORD_ID" \
  --silent \
  --fail \
  -X PUT \
  -d "$_UPDATE" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $API_TOKEN" |
  jq ".result | {zone_id: .zone_id, record_id: .id, ip: .content, record_name: .name, zone_name: .zone_name}" &>$TMP_FILE
